{
  imports = [
    ./analytics
    ./android-updater
    ./artifacts-mirror
    ./bug-tracker
    ./buildbot
    ./central
    ./discord-bot
    ./etherpad
    ./fifoci-frontend
    ./fifoci-worker
    ./flatpak-worker
    ./foreign-builders
    ./mastodon
    ./monitoring
    ./nas-client
    ./netplay-index
    ./oci-registry
    ./redirector
    ./traversal-server
  ];
}
