#! /bin/bash

# Usage: ./send-buildbot-change <revhash> <revhash...>
# Sends the changes associated to a revhash to the buildbot

source $(dirname $0)/config.vars

for r in $*; do
    branch=$(cd $REPO && $BASE/git-what-branch --allbranches $r | cut -d / -f 3- | cut -d '(' -f 1 | xargs echo)
    v=$(cd $REPO && git describe --always --long $r | cut -d - -f -2)
    if ! echo "$branch" | fgrep -q " " 2>/dev/null; then
        author="$(cd $REPO && git log --format=format:"%an" -1 $r)"
        comment="$(cd $REPO && git log --format=format:"%s" -1 $r)"
        buildbot sendchange -m $BUILDBOT_ADDR -a $BUILDBOT_CREDS \
            -W "$author" -s git -r $r \
            -p branchname:$branch -p shortrev:$v -p author:"$author" -p description:"$comment" \
            -l "$URL$r" -c "$comment"
    fi
done
