name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  altair:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build altair.dolphin-emu.org
        run: nix run nixpkgs#colmena -- build --on altair.dolphin-emu.org

  deneb:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build deneb.dolphin-emu.org
        run: nix run nixpkgs#colmena -- build --on deneb.dolphin-emu.org
